### ISSUE TITLE
子项目有一行配置文件没看懂 config.optimization.splitChunks(false)

### ISSUE THREAD

**Issue by qiaokeli111** [zh-rocco/vue-simple-micro-frontends#13]
config.optimization.splitChunks(false)
请问这行代码干什么，我以为是关闭组件拆分，可是为什么要关闭，能不能解释下

**Comment by zh-rocco** [comment]
@qiaokeli111 

关闭 `splitChunks`
![image](https://user-images.githubusercontent.com/23545037/111399627-b0269380-8700-11eb-892e-fe4d6411a071.png)

开启 `splitChunks`
![image](https://user-images.githubusercontent.com/23545037/111399683-cdf3f880-8700-11eb-9a88-c1340916a07a.png)

`splitChunks` 会将项目中的公共依赖提取到 `chunk-vendors.xxxxxxxx.js` 文件中，项目运行我们需要先加载 `chunk-vendors.xxxxxxxx.js`，然后再加载项目的入口文件（`main.js`）。然而子项目中我们需要暴露出去一个独立且完整的 JS 文件，所以就关闭了 `splitChunks`，将 `chunk-vendors.xxxxxxxx.js` 的内容合并至 `main.js`。

补充：[splitChunks 介绍](https://webpack.js.org/plugins/split-chunks-plugin/)
> Since webpack v4, the `CommonsChunkPlugin` was removed in favor of `optimization.splitChunks`.
